#### Setup

Import **NumPY**

In [1]:
import numpy as np #Import NumPY and declare it using an alias

## Matrices (Ch6)

**np.array()** takes several arrays/vectors as arguments:

**A** = np.array( **[ outer brace 1** [inner braces: **row1**], [inner braces: **row2**] **outer brace 2]**)

In [2]:
A = np.array([[0, 1, -2, 1], [1, 2, 3, 4], [4, 2, 3, 1]])
#A.shape returns a tuple of 2 values for the dimensions of A, m x n, as (m, n)

print(A.shape)

m, n = A.shape
print('m:', m)
print('n:', n)


(3, 4)
m: 3
n: 4


#### Indexing Entries

Return the *i*th row and *j*th column entry of matrix **A** using A[i-1, j-1], since Python starts indexing from 0:

In [3]:
A[0, 2] #returns A_1,3, which should be -2

-2

In [4]:
A[0, 2] = 7 #assigns A_1,3 with 7
A

array([[0, 1, 7, 1],
       [1, 2, 3, 4],
       [4, 2, 3, 1]])

#### Row and Column

Depending on the input for **np.array**, we can form either a vector or a 2-dimensional matrix. If you're aiming for the matrix, remember the outer brackets:

In [5]:
 # a: 3-vector
a = np.array([2, 1, 3])
print('dimensions of a:', a.shape)

 # b: 1 x 3 matrix (m x n)
b = np.array([[1, 100, 3]]) # 1 row, 3 columns
print('dimensions of b:', b.shape)

 # c: 3 x 1 matrix (m x n)
c = np.array([[3],[100],[1]]) # 3 rows, 1 column
print('dimensions of c:', c.shape)

dimensions of a: (3,)
dimensions of b: (1, 3)
dimensions of c: (3, 1)


#### Slicing and submatrices

Using appropriate indices, we can extract submatrices:

For example: A[0:2, 2:4] extracts:

rows [1, 3) ("first row inclusive up to 3rd row exclusive", so rows 1 & 2)

cols [2, 4) ("3rd column inclusive up to 5th column exclusive", so cols 3 & 4, there is no 5th col)

In [6]:
print(A)

[[0 1 7 1]
 [1 2 3 4]
 [4 2 3 1]]


In [7]:
print('Submatrix A[0:2, 2:4]:\n', A[0:2, 2:4])
print('dimension of submatrix:\n A[0:2, 2:4]: ', A[0:2, 2:4].shape)

Submatrix A[0:2, 2:4]:
 [[7 1]
 [3 4]]
dimension of submatrix:
 A[0:2, 2:4]:  (2, 2)


#### Block Matrices



In [8]:
B = np.array([0, 2, 3])
C = np.array([-1, 2, 5])

X = np.block([[B], [C]])
print(X)
print(X.shape)
Y = np.block([[B, C]])
print(Y)
print(Y.shape)

[[ 0  2  3]
 [-1  2  5]]
(2, 3)
[[ 0  2  3 -1  2  5]]
(1, 6)


## Zero and Identity Matrices (Ch 6.2)

A zero matrix can be constructed using **np.zeros((m, n))**, where (m, n) is a 2-tuple.

An identity matrix can be constructed using **np.identity(N)**. Identity matrices can only be square, so dimensions are **N x N**

There's no technical term for a matrix consisting of all 1's, but one can be constructed using **np.ones((m, n))**

In [9]:
Z = np.zeros((3, 2))
print('Zero 3 x 2 matrix:')
print(Z)
print(Z.shape, '\n')

I = np.identity(4)
print('Identity 4 x 4 matrix:')
print(I)
print(I.shape, '\n')

O = np.ones((3, 2))
print('Ones 3 x 2 matrix:')
print(O)
print(O.shape)

Zero 3 x 2 matrix:
[[0. 0.]
 [0. 0.]
 [0. 0.]]
(3, 2) 

Identity 4 x 4 matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4) 

Ones 3 x 2 matrix:
[[1. 1.]
 [1. 1.]
 [1. 1.]]
(3, 2)


### Diagonal Matrix

In standard mathematical notation, **diag(1, 2, 3)** is a diagonal 3×3 matrix with diagonal entries 1, 2, 3. In Python, such a matrix can be created using **np.diag(D)**, where D is a square matrix

In [10]:
D = np.array([[1, 3, 5],[0, 2, 4],[9, 8, 3]])
print('Original Matrix:')
print(D, '\n')

print('Diagonal Vector: \nD_11, D_22, D_33')
print(np.diag(D), '\n')

#We can construct a matrix with only the diagonals using the diag function again:
print(np.diag(np.diag(D)))

Original Matrix:
[[1 3 5]
 [0 2 4]
 [9 8 3]] 

Diagonal Vector: 
D_11, D_22, D_33
[1 2 3] 

[[1 0 0]
 [0 2 0]
 [0 0 3]]


### Random Matrices

Random matrix entries are useful for later testing for linear independency between columns, and subsequently QR factorization and inverting matrices.

**np.random.random((m, n))**

In [11]:
R = np.random.random((2, 3))
print('Random 2 x 3 matrix, R:')
print(R)
print(R.shape)

Random 2 x 3 matrix, R:
[[0.13954606 0.97165476 0.14537371]
 [0.05623944 0.99595358 0.66045939]]
(2, 3)


## Transpose, addition, norm (Ch6.3)

#### Transpose

In Python, the transpose of A is given by **np.transpose(A)**, or **A.T** for succinctness.

In [12]:
print(A)

[[0 1 7 1]
 [1 2 3 4]
 [4 2 3 1]]


In [13]:
print(np.transpose(A))

[[0 1 4]
 [1 2 2]
 [7 3 3]
 [1 4 1]]


In [14]:
print(A.T)

[[0 1 4]
 [1 2 2]
 [7 3 3]
 [1 4 1]]


#### Addition

#### Norm

* **skipping for now**

## Matrix-vector Multiplication (Ch6.4)

In Python, matrix-vector mult. has the natural syntax *y = A @ x*

Alternatively, we can use NumPy function **np.matmul(A, x)**, A is an *m x n* matrix, *x* is an *n*-vector, and the output vector *y* is an *m*-vector.

## Matrix-Vector/Matrix Multiplication (Ch6.4, Ch10)

When multiplying a Matrix and a Vector together, you should be thinking about this as simply Matrix-Matrix multiplication. After all, vectors and matrices are one in the same: you may have noticed by now that $n$-vectors are merely $n \times 1$ matrices! This should simplify much of how we think about resultant matrix outputs.

We've read that matrix multiplication *is not commutative*. This is because the dimensions of both matrices determine the dimensions of the output matrix. As you've read, to multiply two matrices together, the inner dimensions must match. In other words:

A matrix, $A$, with dimensions $m \times p$ can only be multiplied by another matrix, $B$, with dimensions $p \times n$. Again, in other words: *The first matrix must have the same number of columns as rows of the second matrix*.

Take the expression $y = Ax$.

* $A$ is an ($m \times n$) matrix.

* $x$ is an $n$-vector, or an $n \times 1$ matrix.

We can now see this as a legal operation: We are multiplying an $m \times n$ matrix with an $n \times 1$ matrix:

$m \times (n * n) \times 1$ --> inner dimensions are equal, and we will output a matrix with the outer dimensions.

The output, $y$, is an $m \times 1$ matrix, or an $m$-vector.

In [20]:
A = np.array([[1,2],[3,4], [5, 6]])
x = np.array([2, 3])

print('Multiplying Ax:')
print('A =')
print(A)
print('x =')
print(x)
print('y = A @ x =', A@x)

## Causes a value error. We are attempting to multiply (n x 1) * (m x n). 
## The inner dimensions do not match. This operation is illegal!
# print(x @ A) 

Multiplying Ax:
A =
[[1 2]
 [3 4]
 [5 6]]
x =
[2 3]
y = A @ x = [ 8 18 28]


## Visualizing the Transpose

Rows become columns:
* First row becomes the first column in the transpose
* Second row becomes the second column in the transpose
* And so on...
Notice that **diagonal entries stay the same**.

In [25]:
x = np.array([2, 3])
x_t = x.T
print(x)
print(x_t)
print(x_t@x)

[2 3]
[2 3]
13


#### Running Sum Matrix

A running sum matrix is a lower triangular matrix, with elements on and below the diagonal equal to one.

In [28]:
def running_sum(n):  # input takes int n, A running sum matrix is a square n x n matrix
    import numpy as np  #in case this isnt already imported
    S = np.zeros((n, n))
    
    #change every S_ij, where j <= i, to  1.
    for i in range(n): #Traverse rows
        for j in range(i + 1): #Traverse columns, going only as far as i does
            S[i, j] = 1 
    
    return S

In [29]:
running_sum(4)

array([[1., 0., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 1., 0.],
       [1., 1., 1., 1.]])

## Matrix Inverses (Ch11)

#### Left and right inverses (Ch11.1)



In [31]:
A = np.array([[-3,-4],[4,6],[1,1]]) # tall matrix, only left inverses exist
B = np.array([[-11,-10,16],[7, 8, -11]])/9 #a left inverse of A
B @ A # close enough :)

array([[ 1.0000000e+00,  0.0000000e+00],
       [-4.4408921e-16,  1.0000000e+00]])

#### Inverse (Ch11.2)

If **A** is invertible, its inverse is given by **np.linalg.inv(A)**. You'll get an error if A is not invertible, or A is not square. 

Conditions for invertibility:
* Invertible: If a matrix A is left-invertible and square, then it is also right-invertible
* If A is left- and right-invertible, then the left and right inverse are unique and equal.
    * Any left inverse of A is equal to any right inverse of A
* Invertible matrices **must be square**


In [34]:
A = np.array([[1,-2,3],[0,2,2],[-4,-4,-4]])
B = np.linalg.inv(A)
print(B)

[[-2.77555756e-17 -5.00000000e-01 -2.50000000e-01]
 [-2.00000000e-01  2.00000000e-01 -5.00000000e-02]
 [ 2.00000000e-01  3.00000000e-01  5.00000000e-02]]


## Solving linear equations

### Back substitution



## WEEK 11 QUIZ

In [35]:
x = -1
y = 3
z = 1

4*x+y+z

0

In [37]:
3*x+4*y+3*z

12

In [38]:
x+y+z

3